### ISSUE TITLE
42 warnings!

### ISSUE THREAD

**Issue by AmilaDiman** [clemensg/sqlite3pod#2]
![screen shot 2015-08-12 at 12 34 23 pm](https://cloud.githubusercontent.com/assets/12527667/9218266/8e4149bc-40ee-11e5-83a8-551bd650b86b.png)

Can you please look into these warnings.
Thanks

**Comment by clemensg** [comment]
Hi,

this is an upstream SQLite problem.
To hide them, you can add `inhibit_all_warnings!` to your Podfile. These clang warnings are harmless and it seems, no one bothered to fix them yet.
Did they show up when building or when using the Xcode analyzer?

You could report those clang warnings on the sqlite-dev mailing list or send a patch to fix the warnings.

**Comment by clemensg** [comment]
CocoaPods can now silence the warnings of one pod alone, so that's definitely preferrable: Please use `pod 'sqlite3', inhibit_warnings: true` if you want to silence them instead of the `inhibit_all_warnings!` method.
You do not need to add it to all subspecs, using `inhibit_warnings: true` once on `pod 'sqlite3'` is enough, no need to also add it to `pod 'sqlite3/fts'` etc.
