### ISSUE TITLE
not working with Xcode 7.1

### ISSUE THREAD

**Issue by casim** [clemensg/sqlite3pod#3]
Since Xcode 7.1 bundle version should be of maximum 3 numbers (even for pods inside projects) so your 3.9.2.0 fails when I try to upload to iTunesConnect

**Comment by clemensg** [comment]
Luckily, SQLite moved to semantic versioning beginning with 3.9.0. We can therefore change the version number and add the two zeros manually to the archive name (because internally, SQLite is still using 3090200 as archive and directory name for the 3.9.2 release...).

I pushed a new version '3.9.2' but this version is not shown as the newest one by CocoaPods, because it is positioned before '3.9.2.0' in ascending sort order.

Until then, please try using the following in your Podfile:
```pod 'sqlite3', '3.9.2', inhibit_warnings: true```

Does this work for you?

**Comment by clemensg** [comment]
Hi @casim, luckily, SQLite is now using 3 numbers. I uploaded a new version of the sqlite3 pod (`3.10.0`).
I am closing this now, because having `pod 'sqlite3', inhibit_warnings: true` in your Podfile works again when pushing applications to the app store.

Please report back if you experience any problems.
